/**
 * PRD Viewer - Display generated PRD document
 */
import { motion } from 'framer-motion';
import { X, Download, Copy, Check, Zap, Brain, FileText } from 'lucide-react';
import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import jsPDF from 'jspdf';

interface PRDViewerProps {
  isOpen: boolean;
  onClose: () => void;
  prdData: any;
}

export const PRDViewer: React.FC<PRDViewerProps> = ({ isOpen, onClose, prdData }) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !prdData) return null;

  const isQuickPRD = prdData.type === 'quick';
  const isDetailedPRD = prdData.sections && Array.isArray(prdData.sections);
  
  const handleCopy = () => {
    let text = '';
    if (isQuickPRD) {
      text = prdData.content || JSON.stringify(prdData, null, 2);
    } else if (isDetailedPRD) {
      text = prdData.fullContent || JSON.stringify(prdData, null, 2);
    } else {
      text = JSON.stringify(prdData, null, 2);
    }
    
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const doc = new jsPDF();
    const filename = `PRD-${new Date().toISOString().split('T')[0]}.pdf`;
    
    let yPosition = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - (margin * 2);
    
    // Helper function to add text with word wrapping
    const addText = (text: string, fontSize: number = 10, isBold: boolean = false) => {
      doc.setFontSize(fontSize);
      if (isBold) doc.setFont('helvetica', 'bold');
      else doc.setFont('helvetica', 'normal');
      
      const lines = doc.splitTextToSize(text, maxWidth);
      lines.forEach((line: string) => {
        if (yPosition > 280) {
          doc.addPage();
          yPosition = 20;
        }
        doc.text(line, margin, yPosition);
        yPosition += fontSize * 0.5;
      });
      yPosition += 5;
    };
    
    // Title
    addText('Product Requirements Document', 16, true);
    addText(`Generated: ${new Date().toLocaleDateString()}`, 10);
    yPosition += 5;
    
    // Content
    if (isQuickPRD && prdData.content) {
      // Remove markdown symbols for PDF
      const cleanContent = prdData.content
        .replace(/^#+\s+/gm, '')  // Remove headers
        .replace(/\*\*/g, '')      // Remove bold
        .replace(/\*/g, '•');      // Convert bullets
      
      const sections = cleanContent.split('\n\n');
      sections.forEach((section: string) => {
        if (section.trim()) {
          const isHeader = section.length < 100 && !section.includes('•');
          addText(section.trim(), isHeader ? 12 : 10, isHeader);
        }
      });
      
      // Add metadata
      if (prdData.metadata) {
        yPosition += 10;
        doc.setDrawColor(200, 200, 200);
        doc.line(margin, yPosition, pageWidth - margin, yPosition);
        yPosition += 10;
        addText(`Model: ${prdData.model_used || 'Unknown'}`, 9);
        addText(`Cost: $${prdData.generation_cost?.toFixed(4) || '0.00'}`, 9);
      }
    } else if (isDetailedPRD) {
      prdData.sections.forEach((section: any, idx: number) => {
        // Section header
        addText(section.title || `Section ${idx + 1}`, 14, true);
        
        // User input
        if (section.userInput) {
          addText('Your Input:', 11, true);
          addText(section.userInput, 10);
        }
        
        // AI Analysis
        if (section.agentAnalysis) {
          addText('AI Analysis:', 11, true);
          const cleanAnalysis = section.agentAnalysis
            .replace(/<think>[\s\S]*?<\/think>/g, '')
            .replace(/^#+\s+/gm, '')
            .replace(/\*\*/g, '')
            .trim();
          addText(cleanAnalysis, 10);
        }
        
        // Mockup info
        if (section.mockup && section.mockup.screens) {
          addText(`Design Mockups: ${section.mockup.screens.length} screen(s) generated`, 10, true);
          if (section.mockup.colorPalette) {
            addText(`Colors: ${section.mockup.colorPalette.primary}, ${section.mockup.colorPalette.accent}`, 9);
          }
        }
        
        yPosition += 10;
      });
    }
    
    // Footer
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by ProdPlex Multi-Agent System', margin, yPosition);
    
    doc.save(filename);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        onClick={onClose}
        className="absolute inset-0 bg-black/80 backdrop-blur-sm"
      />

      {/* Modal */}
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.95 }}
        className="relative w-full max-w-5xl max-h-[90vh] bg-dark-card border-2 border-dark-border rounded-xl shadow-2xl flex flex-col"
      >
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-dark-border">
          <div>
            <h2 className="text-2xl font-display font-bold gradient-text flex items-center gap-2">
              {isQuickPRD ? (
                <>
                  <Zap className="w-6 h-6 text-orange-400" />
                  Quick PRD
                </>
              ) : isDetailedPRD ? (
                <>
                  <Brain className="w-6 h-6 text-purple-400" />
                  Detailed PRD
                </>
              ) : (
                <>
                  <FileText className="w-6 h-6" />
                  Product Requirements Document
                </>
              )}
            </h2>
            <p className="text-xs text-gray-400 mt-1">
              {prdData.title || 'Product Requirements Document'}
            </p>
            {prdData.metadata && (
              <p className="text-xs text-gray-500 mt-1">
                Generated by {prdData.metadata.agents_used?.join(', ') || 'AI'} • 
                {prdData.generated_at && ` ${new Date(prdData.generated_at).toLocaleString()}`}
              </p>
            )}
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="p-2 hover:bg-dark-lighter rounded-lg transition-colors"
              title="Copy to clipboard"
            >
              {copied ? (
                <Check className="w-5 h-5 text-green-400" />
              ) : (
                <Copy className="w-5 h-5 text-gray-400" />
              )}
            </button>
            <button
              onClick={handleDownload}
              className="p-2 hover:bg-dark-lighter rounded-lg transition-colors"
              title="Download PRD"
            >
              <Download className="w-5 h-5 text-gray-400" />
            </button>
            <button
              onClick={onClose}
              className="p-2 hover:bg-dark-lighter rounded-lg transition-colors"
            >
              <X className="w-6 h-6 text-gray-400" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-auto p-6">
          {/* Quick PRD - Markdown Formatted */}
          {isQuickPRD && prdData.content && (
            <div className="prose prose-invert max-w-none">
              <ReactMarkdown
                remarkPlugins={[remarkGfm]}
                components={{
                  h1: ({node, ...props}) => <h1 className="text-3xl font-bold text-white mb-4 pb-2 border-b border-dark-border" {...props} />,
                  h2: ({node, ...props}) => <h2 className="text-2xl font-bold text-white mt-8 mb-3" {...props} />,
                  h3: ({node, ...props}) => <h3 className="text-xl font-semibold text-white mt-6 mb-2" {...props} />,
                  p: ({node, ...props}) => <p className="text-gray-300 mb-3 leading-relaxed" {...props} />,
                  ul: ({node, ...props}) => <ul className="text-gray-300 list-disc list-inside mb-3 space-y-1" {...props} />,
                  ol: ({node, ...props}) => <ol className="text-gray-300 list-decimal list-inside mb-3 space-y-1" {...props} />,
                  li: ({node, ...props}) => <li className="text-gray-300" {...props} />,
                  strong: ({node, ...props}) => <strong className="text-white font-bold" {...props} />,
                  code: ({node, ...props}) => <code className="bg-dark-bg px-2 py-1 rounded text-neon-cyan text-sm" {...props} />,
                  blockquote: ({node, ...props}) => <blockquote className="border-l-4 border-orange-400 pl-4 italic text-gray-400 my-4" {...props} />,
                }}
              >
                {prdData.content}
              </ReactMarkdown>
              
              {/* Metadata Footer */}
              {prdData.metadata && (
                <div className="mt-8 pt-6 border-t border-dark-border">
                  <p className="text-sm text-gray-400">
                    Generated using <span className="text-orange-400 font-semibold">Quick Mode</span> • 
                    Model: <span className="text-gray-300">{prdData.model_used}</span> • 
                    Cost: <span className="text-neon-cyan">${prdData.generation_cost?.toFixed(4) || '0.00'}</span>
                  </p>
                </div>
              )}
            </div>
          )}
          
          {/* Detailed PRD - Section by Section */}
          {isDetailedPRD && (
            <div className="space-y-6">
              {prdData.sections.map((section: any, idx: number) => (
                <div key={idx} className="bg-dark-lighter border border-dark-border rounded-lg p-5">
                  <h3 className="text-lg font-bold text-purple-300 mb-3">{section.title}</h3>
                  
                  {section.userInput && (
                    <div className="mb-3">
                      <p className="text-xs text-gray-500 mb-1">Your Input:</p>
                      <p className="text-sm text-gray-300 bg-dark-bg p-3 rounded">{section.userInput}</p>
                    </div>
                  )}
                  
                  {section.agentAnalysis && (
                    <div>
                      <p className="text-xs text-gray-500 mb-1">AI Analysis:</p>
                      <div className="text-sm text-gray-200 prose prose-invert prose-sm max-w-none">
                        <ReactMarkdown remarkPlugins={[remarkGfm]}>
                          {section.agentAnalysis}
                        </ReactMarkdown>
                      </div>
                    </div>
                  )}
                  
                  {/* Display Mockup if available */}
                  {section.mockup && section.mockup.screens && section.mockup.screens.length > 0 && (
                    <div className="mt-4 pt-4 border-t border-dark-border">
                      <p className="text-xs text-gray-500 mb-3">Design Mockups:</p>
                      <div className="space-y-4">
                        {section.mockup.screens.map((screen: any, screenIdx: number) => (
                          <div key={screenIdx} className="bg-dark-bg rounded-lg p-4">
                            <h4 className="text-sm font-semibold text-white mb-2">{screen.name}</h4>
                            <div className="bg-white rounded p-2">
                              <div 
                                dangerouslySetInnerHTML={{ __html: screen.svg }}
                                className="w-full"
                              />
                            </div>
                            {screen.components && screen.components.length > 0 && (
                              <div className="mt-2">
                                <p className="text-xs text-gray-500 mb-1">Components:</p>
                                <div className="flex flex-wrap gap-1">
                                  {screen.components.map((comp: string, compIdx: number) => (
                                    <span key={compIdx} className="text-xs bg-purple-500/20 text-purple-300 px-2 py-0.5 rounded">
                                      {comp}
                                    </span>
                                  ))}
                                </div>
                              </div>
                            )}
                          </div>
                        ))}
                        
                        {/* Color Palette */}
                        {section.mockup.colorPalette && (
                          <div className="bg-dark-bg rounded-lg p-4">
                            <p className="text-xs text-gray-500 mb-2">Color Palette:</p>
                            <div className="flex gap-2">
                              <div className="text-center">
                                <div 
                                  className="w-16 h-16 rounded border border-dark-border"
                                  style={{ backgroundColor: section.mockup.colorPalette.primary }}
                                />
                                <p className="text-xs text-gray-400 mt-1">Primary</p>
                                <p className="text-xs text-gray-500">{section.mockup.colorPalette.primary}</p>
                              </div>
                              <div className="text-center">
                                <div 
                                  className="w-16 h-16 rounded border border-dark-border"
                                  style={{ backgroundColor: section.mockup.colorPalette.accent }}
                                />
                                <p className="text-xs text-gray-400 mt-1">Accent</p>
                                <p className="text-xs text-gray-500">{section.mockup.colorPalette.accent}</p>
                              </div>
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              ))}
              
              {/* Metadata Footer */}
              <div className="pt-6 border-t border-dark-border">
                <p className="text-sm text-gray-400">
                  Generated using <span className="text-purple-400 font-semibold">Detailed Mode</span> • 
                  {prdData.sections?.length || 9} AI agents collaborated
                </p>
              </div>
            </div>
          )}
          
          {/* Fallback - Raw JSON */}
          {!isQuickPRD && !isDetailedPRD && (
            <div className="prose prose-invert max-w-none">
              <pre className="bg-dark-lighter p-4 rounded-lg text-sm text-gray-300 overflow-x-auto whitespace-pre-wrap">
                {JSON.stringify(prdData, null, 2)}
              </pre>
            </div>
          )}
        </div>
      </motion.div>
    </div>
  );
};

export default PRDViewer;

