/**
 * PRDViewer - Displays and allows download of generated PRD
 */
import { motion } from 'framer-motion';
import { FileText, Download, CheckCircle } from 'lucide-react';
import { useState } from 'react';

interface PRDViewerProps {
  prd: any;
  onClose?: () => void;
}

export const PRDViewer: React.FC<PRDViewerProps> = ({ prd, onClose }) => {
  const [activeSection, setActiveSection] = useState('summary');

  const downloadMarkdown = () => {
    const markdown = prd.markdown || '';
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `PRD-${prd.metadata?.product_name || 'product'}-v${prd.metadata?.version || '1.0'}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const sections = [
    { id: 'summary', label: 'Executive Summary' },
    { id: 'problem', label: 'Problem Statement' },
    { id: 'users', label: 'Target Users' },
    { id: 'requirements', label: 'Requirements' },
    { id: 'design', label: 'Design Specs' },
    { id: 'gtm', label: 'Go-to-Market' },
    { id: 'metrics', label: 'Success Metrics' },
    { id: 'risks', label: 'Risks & Mitigation' },
  ];

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 bg-dark/95 backdrop-blur-sm z-50 overflow-y-auto"
    >
      <div className="min-h-screen p-6">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <motion.div
            initial={{ y: -20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            className="card mb-6"
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 bg-primary/20 border border-primary/30 rounded-lg flex items-center justify-center">
                  <FileText className="w-6 h-6 text-primary-light" />
                </div>
                <div>
                  <h1 className="text-2xl font-display font-bold text-light">
                    Product Requirements Document
                  </h1>
                  <p className="text-sm text-gray-400">
                    {prd.metadata?.product_name || 'Product'} v{prd.metadata?.version || '1.0'}
                  </p>
                </div>
              </div>
              <div className="flex gap-3">
                <button
                  onClick={downloadMarkdown}
                  className="btn btn-primary"
                >
                  <Download className="w-4 h-4" />
                  Download PRD
                </button>
                {onClose && (
                  <button onClick={onClose} className="btn btn-ghost">
                    Close
                  </button>
                )}
              </div>
            </div>
          </motion.div>

          {/* Content */}
          <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
            {/* Navigation */}
            <div className="lg:col-span-1">
              <div className="card sticky top-6">
                <h3 className="text-sm font-semibold text-gray-400 mb-3 uppercase tracking-wide">
                  Sections
                </h3>
                <nav className="space-y-1">
                  {sections.map((section) => (
                    <button
                      key={section.id}
                      onClick={() => setActiveSection(section.id)}
                      className={`w-full text-left px-3 py-2 rounded-lg text-sm transition-colors ${
                        activeSection === section.id
                          ? 'bg-primary/20 text-primary-light border border-primary/30'
                          : 'text-gray-400 hover:bg-dark-lighter hover:text-light'
                      }`}
                    >
                      {section.label}
                    </button>
                  ))}
                </nav>
                
                {/* Generation Info */}
                <div className="mt-6 pt-6 border-t border-dark-border">
                  <div className="flex items-center gap-2 text-xs text-gray-500 mb-2">
                    <CheckCircle className="w-3 h-3" />
                    <span>Generated by {prd.metadata?.agents_used?.length || 0} agents</span>
                  </div>
                  <p className="text-xs text-gray-500">
                    {new Date(prd.metadata?.generated_at).toLocaleString()}
                  </p>
                </div>
              </div>
            </div>

            {/* Main Content */}
            <div className="lg:col-span-3">
              <motion.div
                key={activeSection}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="card"
              >
                {activeSection === 'summary' && (
                  <div>
                    <h2 className="text-xl font-display font-bold text-light mb-4">
                      Executive Summary
                    </h2>
                    <div className="prose prose-invert max-w-none">
                      <p className="text-gray-300 leading-relaxed">
                        {prd.executive_summary?.overview || 'No overview available'}
                      </p>
                      
                      <h3 className="text-lg font-semibold text-light mt-6 mb-3">
                        Key Differentiators
                      </h3>
                      <ul className="space-y-2">
                        {prd.executive_summary?.key_differentiators?.map((diff: string, idx: number) => (
                          <li key={idx} className="text-gray-300">{diff}</li>
                        ))}
                      </ul>
                    </div>
                  </div>
                )}

                {activeSection === 'problem' && (
                  <div>
                    <h2 className="text-xl font-display font-bold text-light mb-4">
                      Problem Statement
                    </h2>
                    <div className="space-y-6">
                      <div>
                        <h3 className="text-lg font-semibold text-light mb-3">
                          User Pain Points
                        </h3>
                        <ul className="space-y-2">
                          {prd.problem_statement?.user_pain_points?.map((pain: string, idx: number) => (
                            <li key={idx} className="text-gray-300 flex items-start gap-2">
                              <span className="text-primary-light mt-1">•</span>
                              <span>{pain}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                      
                      <div>
                        <h3 className="text-lg font-semibold text-light mb-3">
                          Market Gaps
                        </h3>
                        <ul className="space-y-2">
                          {prd.problem_statement?.gaps_in_market?.map((gap: string, idx: number) => (
                            <li key={idx} className="text-gray-300 flex items-start gap-2">
                              <span className="text-primary-light mt-1">•</span>
                              <span>{gap}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  </div>
                )}

                {activeSection === 'users' && (
                  <div>
                    <h2 className="text-xl font-display font-bold text-light mb-4">
                      Target Users & Personas
                    </h2>
                    <div className="space-y-6">
                      {prd.target_users?.primary_personas?.map((persona: string, idx: number) => (
                        <div key={idx} className="p-4 bg-dark-lighter border border-dark-border rounded-lg">
                          <p className="text-gray-300">{persona}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {activeSection === 'requirements' && (
                  <div>
                    <h2 className="text-xl font-display font-bold text-light mb-4">
                      Requirements
                    </h2>
                    <div className="space-y-4">
                      {prd.user_stories?.slice(0, 10).map((story: any, idx: number) => (
                        <div key={idx} className="p-4 bg-dark-lighter border border-dark-border rounded-lg">
                          <h3 className="font-semibold text-light mb-2">
                            {story.id}: {story.title}
                          </h3>
                          <p className="text-sm text-gray-400 mb-3">
                            {story.description}
                          </p>
                          <div className="flex gap-4 text-xs">
                            <span className="badge badge-info">
                              {story.story_points} points
                            </span>
                            <span className="badge badge-success">
                              {story.priority}
                            </span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {activeSection === 'design' && (
                  <div>
                    <h2 className="text-xl font-display font-bold text-light mb-4">
                      Design Specifications
                    </h2>
                    <div className="space-y-4">
                      {prd.design_specifications?.mockups?.map((mockup: any, idx: number) => (
                        <div key={idx} className="p-4 bg-dark-lighter border border-dark-border rounded-lg">
                          <h3 className="font-semibold text-light mb-2">
                            {mockup.screen || mockup.name}
                          </h3>
                          {mockup.figma_url && (
                            <a
                              href={mockup.figma_url}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="text-sm text-primary-light hover:underline"
                            >
                              View in Figma
                            </a>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {activeSection === 'gtm' && (
                  <div>
                    <h2 className="text-xl font-display font-bold text-light mb-4">
                      Go-to-Market Strategy
                    </h2>
                    <div className="space-y-6">
                      {prd.go_to_market?.launch_phases?.map((phase: any, idx: number) => (
                        <div key={idx} className="p-4 bg-dark-lighter border border-dark-border rounded-lg">
                          <h3 className="font-semibold text-light mb-3">
                            {phase.phase}
                          </h3>
                          <ul className="space-y-1">
                            {phase.activities?.map((activity: string, aidx: number) => (
                              <li key={aidx} className="text-sm text-gray-300">
                                {activity}
                              </li>
                            ))}
                          </ul>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {activeSection === 'metrics' && (
                  <div>
                    <h2 className="text-xl font-display font-bold text-light mb-4">
                      Success Metrics
                    </h2>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      {Object.entries(prd.success_metrics?.targets || {}).map(([key, value]) => (
                        <div key={key} className="p-4 bg-dark-lighter border border-dark-border rounded-lg">
                          <p className="text-sm text-gray-400 mb-1">
                            {key.replace(/_/g, ' ').toUpperCase()}
                          </p>
                          <p className="text-xl font-semibold text-light">
                            {String(value)}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {activeSection === 'risks' && (
                  <div>
                    <h2 className="text-xl font-display font-bold text-light mb-4">
                      Risks & Mitigation
                    </h2>
                    <div className="mb-6 p-4 bg-dark-lighter border border-dark-border rounded-lg">
                      <p className="text-sm text-gray-400 mb-1">Overall Risk Score</p>
                      <p className="text-3xl font-bold text-light">
                        {prd.risks_and_mitigation?.overall_risk_score || 0}/10
                      </p>
                    </div>
                    <div className="space-y-4">
                      {prd.risks_and_mitigation?.risk_categories?.map((risk: any, idx: number) => (
                        <div key={idx} className="p-4 bg-dark-lighter border border-dark-border rounded-lg">
                          <h3 className="font-semibold text-light mb-2">
                            {risk.category}
                          </h3>
                          <span className={`badge ${
                            risk.risk_level === 'high' ? 'badge-error' :
                            risk.risk_level === 'medium' ? 'badge-warning' :
                            'badge-success'
                          }`}>
                            {risk.risk_level} risk
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </motion.div>
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
};

export default PRDViewer;

