"""
GTM Agent - Crafts go-to-market and launch plans
"""
from typing import Dict, Any, List
from .base_agent import BaseAgent


class GtmAgent(BaseAgent):
    """Agent specialized in go-to-market strategy and launch planning"""
    
    def __init__(self, context: Dict[str, Any] = None):
        super().__init__(
            name="GtmAgent",
            goal="Create comprehensive go-to-market and launch strategies",
            context=context,
            agent_key="gtm"
        )
    
    async def execute(self, task_input: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute GTM-related tasks
        
        Args:
            task_input: Contains task_type and relevant parameters
                - task_type: "launch_plan", "marketing_strategy", "pricing"
                - product: Product name/description
                - target_audience: Target audience details
        """
        self.update_status("running")
        
        task_type = task_input.get("task_type", "launch_plan")
        product = task_input.get("product", "ProdigyPM")
        target_audience = task_input.get("target_audience", "Product Managers")
        
        try:
            if task_type == "launch_plan":
                result = await self._create_launch_plan(product, target_audience)
            elif task_type == "marketing_strategy":
                result = await self._marketing_strategy(product, target_audience)
            elif task_type == "pricing":
                result = await self._pricing_strategy(product)
            elif task_type == "messaging":
                result = await self._create_messaging(product, target_audience)
            else:
                result = await self._general_gtm(task_input)
            
            self.update_context("gtm_strategy", result)
            
            self.update_status("completed")
            return self.format_output(result, {"task_type": task_type})
            
        except Exception as e:
            self.update_status("failed")
            return self.format_output(
                {"error": str(e)},
                {"task_type": task_type, "error": True}
            )
    
    async def _create_launch_plan(self, product: str, audience: str) -> Dict[str, Any]:
        """Create comprehensive launch plan"""
        prompt = f"""Create a comprehensive go-to-market launch plan for the product: {product}, targeting: {audience}.

Please provide a detailed launch plan including:
1. Pre-launch phase (activities, goals, channels, timeline)
2. Launch week strategy (activities, goals, channels)
3. Post-launch phase (activities, goals, channels, timeline)
4. Success metrics (primary and secondary KPIs)
5. Budget allocation recommendations
6. Key messaging and positioning
7. Launch channels and tactics

Format your response as structured, actionable recommendations. Be specific and detailed."""
        
        llm_response = await self._call_llm(prompt, use_nemotron=True)
        
        # Parse and structure the LLM response
        return {
            "product": product,
            "target_audience": audience,
            "launch_plan": llm_response,
            "analysis": "Generated by NVIDIA Nemotron AI model",
            "raw_response": llm_response
        }
    
    async def _marketing_strategy(self, product: str, audience: str) -> Dict[str, Any]:
        """Create marketing strategy"""
        prompt = f"""Create a comprehensive marketing strategy for the product: {product}, targeting: {audience}.

Please provide:
1. Product positioning statement
2. Key value propositions (3-5 compelling benefits)
3. Target customer personas
4. Marketing channels and tactics
5. Content strategy
6. Messaging framework
7. Competitive differentiation

Be specific and actionable."""
        
        llm_response = await self._call_llm(prompt, use_nemotron=True)
        
        return {
            "product": product,
            "target_audience": audience,
            "marketing_strategy": llm_response,
            "analysis": "Generated by NVIDIA Nemotron AI model",
            "raw_response": llm_response
        }
    
    async def _pricing_strategy(self, product: str) -> Dict[str, Any]:
        """Create pricing strategy"""
        prompt = f"""Create a comprehensive pricing strategy for the product: {product}.

Please provide:
1. Recommended pricing model (freemium, subscription, usage-based, etc.)
2. Pricing tiers with specific pricing points
3. Features for each tier
4. Value justification for each tier
5. Competitive pricing analysis
6. Pricing psychology and positioning
7. Revenue projections

Be specific with dollar amounts and feature sets."""
        
        llm_response = await self._call_llm(prompt, use_nemotron=True)
        
        return {
            "product": product,
            "pricing_strategy": llm_response,
            "analysis": "Generated by NVIDIA Nemotron AI model",
            "raw_response": llm_response
        }
    
    async def _create_messaging(self, product: str, audience: str) -> Dict[str, Any]:
        """Create messaging framework"""
        prompt = f"""Create a comprehensive messaging framework for the product: {product}, targeting: {audience}.

Please provide:
1. Headline and tagline
2. Elevator pitch (30 seconds)
3. Value proposition statement
4. Key messaging points
5. Benefits hierarchy (primary, secondary, tertiary)
6. Proof points and evidence
7. Tone and voice guidelines
8. Call-to-action recommendations

Make it compelling and differentiated."""
        
        llm_response = await self._call_llm(prompt, use_nemotron=True)
        
        return {
            "product": product,
            "target_audience": audience,
            "messaging_framework": llm_response,
            "analysis": "Generated by NVIDIA Nemotron AI model",
            "raw_response": llm_response
        }
    
    async def _general_gtm(self, task_input: Dict[str, Any]) -> Dict[str, Any]:
        """Handle general GTM tasks"""
        task = task_input.get("task", "General GTM task")
        product = task_input.get("product", task_input.get("feature", "Product"))
        prompt = f"""Complete this go-to-market task: {task}

Product/Feature: {product}
Context: {task_input}

Please provide a comprehensive, detailed response with actionable recommendations."""
        
        llm_response = await self._call_llm(prompt, use_nemotron=True)
        
        return {
            "task": task,
            "product": product,
            "output": llm_response,
            "analysis": "Generated by NVIDIA Nemotron AI model"
        }

