"""
Story Export Utilities - CSV, JSON, Markdown

Matches PNC workshop export format expectations
Demonstrates compatibility with standard PM tools
"""
import csv
import json
from typing import List, Dict, Any
from datetime import datetime
from io import StringIO
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


class StoryExporter:
    """Export user stories in multiple formats for PM tools"""
    
    @staticmethod
    def to_csv(stories: List[Dict[str, Any]]) -> str:
        """
        Export stories to CSV format (PNC workshop compatible)
        
        Args:
            stories: List of story dictionaries
            
        Returns:
            CSV string
        """
        if not stories:
            return ""
        
        output = StringIO()
        
        # Define CSV columns matching PNC format
        fieldnames = [
            'title',
            'description',
            'acceptance_criteria',
            'priority',
            'estimate',
            'tags',
            'epic',
            'author',
            'status',
            'jira_key',
            'generated_at'
        ]
        
        writer = csv.DictWriter(output, fieldnames=fieldnames)
        writer.writeheader()
        
        for story in stories:
            # Format acceptance criteria as numbered list
            ac_text = "; ".join([
                f"{i+1}. {criterion}" 
                for i, criterion in enumerate(story.get('acceptance_criteria', []))
            ])
            
            # Format tags as comma-separated
            tags_text = ", ".join(story.get('tags', []))
            
            writer.writerow({
                'title': story.get('title', ''),
                'description': story.get('description', ''),
                'acceptance_criteria': ac_text,
                'priority': story.get('priority', 'Medium'),
                'estimate': story.get('estimate', ''),
                'tags': tags_text,
                'epic': story.get('epic', ''),
                'author': story.get('author', 'ProdPlex AI'),
                'status': story.get('status', 'Draft'),
                'jira_key': story.get('jira_key', ''),
                'generated_at': story.get('generated_at', datetime.now().isoformat())
            })
        
        return output.getvalue()
    
    @staticmethod
    def to_markdown(stories: List[Dict[str, Any]], title: str = "User Stories") -> str:
        """
        Export stories to Markdown format (PNC workshop compatible)
        
        Args:
            stories: List of story dictionaries
            title: Document title
            
        Returns:
            Markdown string
        """
        if not stories:
            return "# No stories to export\n"
        
        lines = [
            f"# {title}",
            f"",
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}  ",
            f"**Total Stories:** {len(stories)}  ",
            f"**Generated By:** ProdPlex 9-Agent AI System  ",
            f"",
            "---",
            ""
        ]
        
        for idx, story in enumerate(stories, 1):
            lines.append(f"## {idx}. {story.get('title', 'Untitled Story')}")
            lines.append("")
            
            # Metadata
            lines.append("**Metadata:**")
            if story.get('jira_key'):
                lines.append(f"- **Jira Key:** `{story['jira_key']}`")
            lines.append(f"- **Priority:** {story.get('priority', 'Medium')}")
            lines.append(f"- **Estimate:** {story.get('estimate', 'N/A')}")
            lines.append(f"- **Epic:** {story.get('epic', 'N/A')}")
            lines.append(f"- **Status:** {story.get('status', 'Draft')}")
            if story.get('tags'):
                tags = ", ".join([f"`{tag}`" for tag in story['tags']])
                lines.append(f"- **Tags:** {tags}")
            lines.append("")
            
            # Description
            lines.append("**Description:**")
            lines.append(story.get('description', 'No description provided'))
            lines.append("")
            
            # Acceptance Criteria
            if story.get('acceptance_criteria'):
                lines.append("**Acceptance Criteria:**")
                for criterion in story['acceptance_criteria']:
                    lines.append(f"- [ ] {criterion}")
                lines.append("")
            
            # AI Enhancement Info
            if story.get('ai_enhanced'):
                lines.append("**AI Enhancement:**")
                lines.append("✨ *Generated by ProdPlex 9-Agent System with:*")
                for advantage in story.get('advantages', []):
                    lines.append(f"  - {advantage}")
                lines.append("")
            
            lines.append("---")
            lines.append("")
        
        return "\n".join(lines)
    
    @staticmethod
    def to_json(stories: List[Dict[str, Any]], pretty: bool = True) -> str:
        """
        Export stories to JSON format
        
        Args:
            stories: List of story dictionaries
            pretty: Whether to pretty-print
            
        Returns:
            JSON string
        """
        data = {
            "generated_at": datetime.now().isoformat(),
            "total_stories": len(stories),
            "generated_by": "ProdPlex 9-Agent AI System",
            "format_version": "1.0",
            "pnc_workshop_compatible": True,
            "stories": stories
        }
        
        if pretty:
            return json.dumps(data, indent=2)
        else:
            return json.dumps(data)
    
    @staticmethod
    def to_jira_import_csv(stories: List[Dict[str, Any]]) -> str:
        """
        Export in Jira CSV import format
        
        This format can be directly imported into Jira
        """
        output = StringIO()
        
        # Jira import columns
        fieldnames = [
            'Summary',
            'Description',
            'Issue Type',
            'Priority',
            'Story Points',
            'Labels',
            'Epic Link',
            'Status'
        ]
        
        writer = csv.DictWriter(output, fieldnames=fieldnames)
        writer.writeheader()
        
        for story in stories:
            # Format description with acceptance criteria for Jira
            description = story.get('description', '')
            if story.get('acceptance_criteria'):
                description += "\n\n*Acceptance Criteria:*\n"
                for i, criterion in enumerate(story['acceptance_criteria'], 1):
                    description += f"{i}. {criterion}\n"
            
            # Extract story points from estimate
            estimate = story.get('estimate', '0sp')
            story_points = ''.join(filter(str.isdigit, estimate)) or '0'
            
            writer.writerow({
                'Summary': story.get('title', ''),
                'Description': description,
                'Issue Type': 'Story',
                'Priority': story.get('priority', 'Medium'),
                'Story Points': story_points,
                'Labels': ','.join(story.get('tags', [])),
                'Epic Link': story.get('epic', ''),
                'Status': story.get('status', 'To Do')
            })
        
        return output.getvalue()


# Global exporter instance
exporter = StoryExporter()

